Algoritmo "semnome"

Var
// Seção de Declarações das variáveis 
p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15 : caracter
c1, c2, c3, c4, c5, c6, c7, c8, c9, c10,c11, c12, c13, c14, c15 : inteiro
m1, m2, m3, m4, m5, m6, m7, m8, m9, m10,m11, m12, m13, m14, m15 : inteiro
media, centralmediana : real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
c1<-5253766
c2<-3057470
c3<-2287511
c4<-897599
c5<-563598
c6<-485836
c7<-483133
c8<-397623
c9<-375044
c10<-370060
c11<-331189
c12<-311641
c13<-291468
c14<-285191
c15<-263503



p1<-("USA")
 p2<-("Brazil")
 p3<-("India")
 p4<-("Russia")
 p5<-("South Africa")
 p6<-("Mexico")
 p7<-("Peru")
 p8<-("Colombia")
 p9<-("Chile")
 p10<-("Spain")
 p11<-("Iran")
 p12<-("UK")
 p13<-("Saudi Arabia")
 p14<-("Pakistan")
 p15<-("Bangladesh")


m1<-166274
m2<-101857
m3<-45550
m4<-15131
m5<-10621
m6<-53003
m7<-21276
m8<-13154
m9<-10139
m10<-28576
m11<-18800
m12<-46526
m13<-3233
m14<-6112
m15<-3471

escreval("=============================================")
escreval("País:  ", "   Casos de Covid: "," Casos de morte:")
escreval(p1,"          ",c1,"         ", m1)
escreval(p2,"       ",c2,"         ", m2)
escreval(p3,"        ",c3,"         ", m3)
escreval(p4,"       ",c4,"          ", m4)
escreval(p5," ",c5,"          ", m5)
escreval(p6,"       ",c6,"          ", m6)
escreval(p7,"         ",c7,"          ", m7)
escreval(p8,"     ",c8,"          ", m8)
escreval(p9,"        ",c9,"          ", m9)
escreval(p10,"        ",c10,"          ", m10)
escreval(p11,"         ",c11,"          ", m11)
escreval(p12,"           ",c12,"          ", m12)
escreval(p13," ",c13,"          ", m13)
escreval(p14,"     ",c14,"          ", m14)
escreval(p15,"   ",c15,"          ", m15)
escreval("==============================================")

media<- (c1+c2+c3+c4+c5+c6+c7+c8+c9+c10+c11+c12+c13+c14+c15) /15

escreval(" A média de casos entre esses países é:", media)

escreval(" A mediana de mortes é:", m8)




Fimalgoritmo