Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]

Var
// Seção de Declarações das variáveis 
 iniciar, parar : inteiro
 v1: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...



escreval("Digite 1 para iniciar o cronometro")
leia(iniciar)


enquanto parar<2 faca

enquanto iniciar=1 faca
v1<- v1+0.001
fimenquanto

fimenquanto

escreval("digite2 para parar")
leia(parar)



Fimalgoritmo