Algoritmo "semnome"

Var
// Seção de Declarações das variáveis 

num: vetor [0..9] de inteiro
i: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

para i de 0 ate 9 faca
escreval("Digite um número inteiro")
leia(num[i])
fimpara

escreval("Processando")
escreval("")

escreval("=========================")

para i de 0 ate 9 faca
escreval(num[i])
fimpara


Fimalgoritmo