Algoritmo "semnome"

Var
p1,p2,p3 : real
aluno: caracter


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval("Qual o nome do aluno?")
leia(aluno)
escreval("Processo......")

escreval("Qual é a nota da primeira prova?")
leia(p1)
escreval("Qual foi a nota da segunda prova?")
leia(p2)
escreval("Qual foi a nota da terceira prova?")
leia(p3)

escreval("A nota deste aluno foi", (p1*2)+(p2*3)+(p3*5)/10)



Fimalgoritmo