Algoritmo "semnome"

Var
// Seção de Declarações das variáveis 

valores1, enc1, vt1: vetor [0..1] de real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Digite o primeiro número:")
 leia(valores1[0] )
 escreval("Digite o segundo número:")
 leia(valores1[1] )
 
 enc1[0]<-valores1[0]
 enc1[1]<-valores1[1]
 vt1[0]<-valores1[0]+valores1[0]
  vt1[1]<-enc1[0]+enc1[1]
  
  
  escreval("A soma é: ",  vt1[1])
 
 





Fimalgoritmo
